### ISSUE TITLE
FAQ: mention that `dotAll` does not affect what is considered a line terminator

### ISSUE THREAD

**Issue by rauschma** [tc39/proposal-regexp-dotall-flag#10]
In Sect. “How does `dotAll` mode affect `multiline` mode?” of the FAQ, it may make sense to mention that `dotAll` does not change that the following characters are _not_ considered line terminators by `^` and `$` in `multiline` mode (right?):

* U+000B VERTICAL TAB (`\v`)
* U+000C FORM FEED (`\f`)
* U+0085 NEXT LINE

It feels like the readme raised a problem at the beginning and should come back to that problem at the end.

**Comment by mathiasbynens** [comment]
Isn’t this already covered by the last two paragraphs in https://github.com/tc39/proposal-regexp-dotall-flag#how-does-dotall-mode-affect-multiline-mode?

> Both modes are independent and can be combined. `multiline` mode only affects anchors, and **`dotAll` mode only affects `.`**.
>
> When both the `s` (`dotAll`) and `m` (`multiline`) flags are set, `.` matches any character while still allowing `^` and `$` to match, respectively, just after and just before line terminators within the string.

Those three additional line-terminator-but-not-in-JS characters are mentioned to make this point:

> By design, it excludes some newline characters, but not all of them, which often does not match the developer’s use case.
