### ISSUE TITLE
We should use "dotall" rather than "singleline"

### ISSUE THREAD

**Issue by claudepache** [tc39/proposal-regexp-dotall-flag#5]
because "singleline" is much less suggestive about the semantics of the flag, and because, it is confusingly independent of  the existing "multiline" flag.

**Comment by mathiasbynens** [comment]
I was wondering about this too, but decided to follow the established tradition of using `s` / `singleline` for the initial proposal.

Do you mean the flag should be changed from `s` to `d` as well? ECMASCript would then be the first/only language with a `d` flag for regular expressions. 

Would the accessor checking for it be named `dotall` or `dotAll` (matching `ignoreCase`)?

**Comment by claudepache** [comment]
I mean that the flag should remain `/s`, but the name of the accessor checking for it should be `RegExp.#dotAll`.

**Comment by timmarinin** [comment]
^ naming flag `s` and getter `dotAll` would be confusing. (UPD: but apparently that's the way [PHP does it](http://php.net/manual/en/reference.pcre.pattern.modifiers.php))

**Comment by claudepache** [comment]
Question: What do implementations that use "dotall"?

**Comment by developit** [comment]
I get the s -> singleline correlation, but singleline just doesn't really indicate what is being modified by the modifier.  `dotAll` seems really obvious.

**Comment by mathiasbynens** [comment]
Sounds like everyone agrees that `dotAll` is more obvious. One question remains: is it acceptable to name the flag `s` when the accessor is named `dotAll`?

**Comment by claudepache** [comment]
If I believe, well, [README.md in this repo](https://github.com/mathiasbynens/es-regexp-singleline-flag/blob/master/README.md), there are precedents of simultaneous uses of `DOTALL` and `s` (Java, Python). Are there precedents of other flags than `s` for that feature?

**Comment by mathiasbynens** [comment]
> Are there precedents of other flags than `s` for that feature?

Not that I know of.

Still, `s` would be the first regex flag in ECMAScript that doesn’t occur in its accessor name.
- `g` → <code>**g**lobal</code>
- `i` → <code>**i**gnoreCase</code>
- `m` → <code>**m**ultiline</code>
- `y` → <code>stick**y**</code>
- `u` → <code>**u**nicode</code>
- `s` → <code>dotAll</code>

…but then again, maybe that’s not a big deal.

CC’ing V8 regexpert @hashseed who might have an opinion on this.

**Comment by bterlson** [comment]
I agree that dotAll is a much better full name. It's actually a good name - a mere 6 characters that describe pretty completely what the flag does. Not sure the best mapping to a flag is though. /s might be ok - there comes a time in many a CLI tool's lifetime where it needs to add an option and there are no obvious corresponding flag forms available. Given the history of using /s for this purpose, I think it's fine to go with that.
