### ISSUE TITLE
Please transfer repository to tc39

### ISSUE THREAD

**Issue by erights** [tc39/proposal-regexp-dotall-flag#7]
See https://github.com/tc39/proposals/issues/44

**Comment by mathiasbynens** [comment]
The repository has been moved, thanks to @littledan.

@bterlson Could you please rename the repository from `es-regexp-dotall-flag` to `proposal-regexp-dotall-flag` (to match https://github.com/tc39/proposal-regexp-unicode-property-escapes), or give me permissions to do so myself?

Once that’s done, I’ll generate new SSH keys for the CI and update the links across this repo.

**Comment by bterlson** [comment]
Done. @mathiasbynens I've also made you an admin of this repo so you should be able to add SSH keys and such.
